### ISSUE TITLE
enhancement of task-5

### ISSUE THREAD

**Issue by mrshi** [xueqianban5s/stage1#9]
@labs00 
- look at the title of task-5...

![image](https://cloud.githubusercontent.com/assets/3349915/14210511/dc07c5b6-f85b-11e5-9b63-30a7b8139aa5.png)
- the tab is not in its correct position, should in the middle of nav, the list-style should be none.

![image](https://cloud.githubusercontent.com/assets/3349915/14210584/3c38ac0c-f85c-11e5-94f7-f1a87ebb0ea1.png)
- the form tips split in 2 lines, a little strange?

![image](https://cloud.githubusercontent.com/assets/3349915/14210653/8a78c8a2-f85c-11e5-97de-f4b1705f8dbd.png)

**Comment by labs00** [comment]
The  problem above has been solved.

**Comment by mrshi** [comment]
:ok_hand:
